# eureka register
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'  # all endpoint

# open api
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html