server:
  port: 8080
  servlet:
    context-path: /

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/v1/loan-types/**
