server:
  port: 8080
  servlet:
    context-path: /

spring:
  redis:
    port: 6379
    host: localhost
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/v1/loan-types/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10 # token/second
                redis-rate-limiter.burstCapacity: 20 # capacity of bucket
                redis-rate-limiter.requestedTokens: 1 # token / request
            - KeyAuthFilter

apiKey: chaoweiz