server:
  port: 9000
  servlet:
    context-path: /

spring:
  mail:
    default-encoding: utf-8
    username: luutrieuvi2003@gmail.com
    password: bacrofozncoqsiqg
    port: 587
    host: smtp.gmail.com
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  boot:
    admin:
      notify:
        mail:
          enabled: true
          to: luutrieuvi2003@gmail.com