spring:
  application:
    name: notification-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true # the service will not run if it can't reach the config-service

