application:
  security:
    jwt:
      secret-key: 51N4xEkSoctoo5LU+3i27/m/tNPcfuFLB1LK4aOkEvaO7arr4JPuRST1NeSvXKdAocBWabXwaceGQTu4HmyrSQ==
      expiration: 24
      refresh-token:
        expiration: 15

open:
  ai:
    title: API Document
    version: v1.0.0
    description: API for finance document

spring:
  application:
    name: finance-management
  datasource:
    url: jdbc:mysql://localhost:3306/finance_management
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
