spring:
  application:
    name: discovery-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true

# config eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
